<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="10.3.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NinePSharp.Fog.Server\NinePSharp.Fog.Server.csproj" />
    <PackageReference Include="NinePSharp.Namespaces.Authorization" Version="$(NinePSharpVersion)" />
    <PackageReference Include="NinePSharp.Namespaces.Orleans" Version="$(NinePSharpVersion)" />
    <PackageReference Include="NinePSharp.Namespaces.Orleans.Server" Version="$(NinePSharpVersion)" />
  </ItemGroup>

</Project>
